config/routes.rb
Rails.application.routes.draw do
  get 'home/default'
  
  namespace :api, defaults: {format: "json"} do
    namespace :v1 do
      resources :messages
      resources :money_txns
    end
  end

  resources :homes 
  resources :messages, except: [:edit, :update]
  resources :money_txns, except: [:new, :show]
  devise_for :users, controllers: {registrations: 'registrations'}

  root 'home#default'

end

app/models/message.rb
class Message < ActiveRecord::Base
	has_many :money_txns, dependent: :destroy
	belongs_to :user

	validates_presence_of :msg_date_time, :subject, :message, :msg_receiver, :user_id
end

app/models/money_txn.rb
class MoneyTxn < ActiveRecord::Base
	belongs_to :message
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages

  validates_presence_of :first_name, :last_name, :dob
  
  before_create :generate_access_token

  private

  def generate_access_token
  	counter = 0
    while counter == 0
      self.access_token = SecureRandom.hex
      if User.pluck(:access_token).include?(self.access_token)
        counter = 0
      else
        counter = 1
      end 
    end
  end
  
end

app/controllers/api/v1/messages_controller.rb
module Api
	module V1
		class MessagesController <ApplicationController
			before_action :check_access_token
			
			def index
				if !@user.nil?
					@messages = Message.where('msg_receiver = ? OR user_id = ?', @user.id, @user.id)
				end
			end

			def show
				if !@user.nil?
					@message = Message.find(params[:id])
				end
			end
					
			private

			def check_access_token
				if params[:access_token]
					@user = User.find_by_access_token(params[:access_token])
				end
				return @user
			end
		end
	end
end

app/controllers/api/v1/money_txns_controller.rb
module Api
	module V1
		class MoneyTxnsController < ApplicationController
			before_action :check_access_token
			
			def index
				if !@user.nil?
					@money_txns = MoneyTxn.where('paid_to = ? OR received_from = ?', @user.id, @user.id)
				end
			end

			private
			
			def check_access_token
				if params[:access_token]
					@user = User.find_by_access_token(params[:access_token])
				end
				return @user
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def default
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	
	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params)
		@message.user_id = current_user.id
		@message.msg_status = false
		if @message.save
			if @message.sent_money == true
				redirect_to message_path(@message.id), notice: "Message created successfully, add payments"
			else
				redirect_to messages_path, notice: "Message sent successfully"
			end
		else
			render action: "new", notice: "Message could not be sent, please try again"
		end
	end

	def show
		@message = Message.find(params[:id])
		if @message.msg_receiver == current_user.id
			@message.update_attributes(msg_status: true)
		end
		@money_txn = MoneyTxn.new
	end

	def index
		@received_messages = Message.where('msg_receiver = ?', current_user.id)
		@sent_messages = current_user.messages
	end
	
	def destroy
		@message = Message.find(params[:id])
		if @message.msg_status == true
			redirect_to messages_path, notice: "Message already read, can't be deleted"
		else
			@message.destroy
			redirect_to messages_path, notice: "Message deleted successfully"
		end
	end

	private
		
	def message_params 
		params[:message].permit(:msg_date_time,:subject,:message,:msg_receiver,:msg_status,:sent_money,:user_id)
	end
end

app/controllers/money_txns_controller.rb
class MoneyTxnsController < ApplicationController
	before_action :authenticate_user!

	def create
		@money_txn = MoneyTxn.new(money_txn_params)
		if @money_txn.save
			redirect_to message_path(@money_txn.message_id), notice: "Transfer Txn successfully added"
		else
			redirect_to message_path(@money_txn.message_id), notice: "Transfer Txn could not be added"
		end
	end

	def destroy
		@money_txn = MoneyTxn.find(params[:money_txn_id])
		@money_txn.destroy
		redirect_to message_path(@money_txn.message_id), notice: "Transfer Txn Successfully deleted"
	end

	def index
		@received_money_txns = MoneyTxn.where('paid_to = ?', current_user.id)
		@paid_money_txns = MoneyTxn.where('received_from = ?', current_user.id)
	end

	private

	def money_txn_params
		params[:money_txn].permit(:currency, :amt, :message_id, :received_from, :paid_to)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def edit
		@user = User.find(current_user.id)
	end

	def update
		@user = User.find(current_user.id)
		if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
    		params[:user].delete(:password)
    		params[:user].delete(:password_confirmation)
		end
		
		if @user.update_attributes(sign_up_params)
			redirect_to new_user_session_path, notice: "User Details Updated Successfully"
		else
			render action: "edit"
		end
	end

	private

	def sign_up_params
		params[:user].permit(:first_name,:last_name,:dob,:email,:password,:confirm_password)		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/money_txns_helper.rb
module MoneyTxnsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
  <script src="//cdn.datatables.net/plug-ins/1.10.15/sorting/datetime-moment.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>

<div class="container-fluid">
  <% if user_signed_in? %>
  <nav class="navbar navbar-default" class="margin">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Messages", messages_path %></li>
        <li><%= link_to "Payments/Receipts", money_txns_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
       
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Account Setting", edit_user_registration_path %> </li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>  </li>
   
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
<% else %>
   <nav class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Messaging and Payment</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/sign_in">Login</a></li>
        <li><a href="/users/sign_up">Sign Up</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
<% end %>

<% if alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>


<%= yield %>


 

</div><!-- container-fluid end here -->

</body>
</html>

app/views/messages/index.html.erb
<div class="page-header" class="margin">
	<h3>
		Messages
		<div class="pull-right">
			<%= link_to new_message_path, class: "btn btn-primary" do %>
			<i class="glyphicon glyphicon-plus"></i> New Message
		<% end %>
		</div>
	</h3> 
</div>

<h4>Inbox</h4>
<table class="table table-stripped" id="messagesInboxTable" width="100%" border="0" cellspacing="0" cellpadding="0">
 <thead>
 	<tr>
 		<th>Date</th>
 		<th>From</th>
 		<th>Subject</th>
 		<th>Included Money?</th>
 		<th>Status</th>
 		<th>Action</th>
 	</tr>
 </thead>
 <tbody>
 	<% @received_messages.each do |received_message| %>
 	<tr>
 		<td><%= received_message.msg_date_time.strftime("%d-%b-%y %H:%M:%S") %></td>
 		<td><%= received_message.user.first_name %></td>
 		<td><%= received_message.subject %></td>
 		<% if received_message.sent_money == true %>
 			<td><%= "Yes" %></td>
 		<% else %>
 			<td><%= "No" %></td>
 		<% end %>
 		<% if received_message.msg_status == false %>
 			<td><%= "New" %></td>
 		<% else %>
 			<td><%= "Read" %></td>
 		<% end %>
 		<td><%= link_to message_path(received_message.id), class: "btn btn-info btn-xs" do %>
 				<i class="glyphicon glyphicon-info-sign">View</i>
 			<% end %>
 		</td>
 	</tr>
 	<% end %>
 </tbody>
 </table>

<h4>Outbox</h4>
 <table class="table table-stripped" id="messagesOutboxTable" width="100%" border="0" cellspacing="0" cellpadding="0">
 <thead>
 	<tr>
 		<th>Date</th>
 		<th>To</th>
 		<th>Message</th>
 		<th>Included Money?</th>
 		<th>Status</th>
 		<th>Action</th>
 	</tr>
 </thead>
 <tbody>
 	<% @sent_messages.each do |sent_message| %>
 	<tr>
 		<td><%= sent_message.msg_date_time.strftime("%d-%b-%y %H:%M:%S") %></td>
 		<td><%= User.find(sent_message.msg_receiver).first_name %></td>
 		<td><%= sent_message.message %></td>
 		<% if sent_message.sent_money == true %>
 			<td><%= "Yes" %></td>
 		<% else %>
 			<td><%= "No" %></td>
 		<% end %>
 		<% if sent_message.msg_status == false %>
 			<td><%= "New" %></td>
 			<td><%= link_to message_path(sent_message.id), class: "btn btn-info btn-xs" do %>
 				<i class="glyphicon glyphicon-info-sign">View</i>
 				<% end %>
 				<%= link_to message_path(sent_message.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" do %>
	 				<i class="glyphicon glyphicon-remove-sign">Delete</i>
	 			<% end %>
 			</td>
 		<% else %>
 			<td><%= "Read" %></td>
 			<td><%= link_to message_path(sent_message.id), class: "btn btn-info btn-xs" do %>
 				<i class="glyphicon glyphicon-info-sign">View</i>
 			<% end %>
 			</td>
 		<% end %>
 		
 	</tr>
 	<% end %>
 </tbody>
 </table>

app/views/messages/new.html.erb
<% if @message.errors.any? %>
	<div class="alert alert-danger">
		<h3> These errors prohibiated the form from being saved </h3>
		<ul>
			<% @message.errors.full_messages.each do |error| %>
				<li> <%= error %></li>
			<% end %>
		</ul>
	</div>
<% end %>


<%= form_for @message do |f| %>

<div class="form-group">
<%= f.label :'Send To' %>
<%= f.collection_select :msg_receiver, User.all, :id, :first_name, {prompt: "Select User"}, {class: "form-control chosen-select"} %>
</div>

<div class="form-group">
<%= f.label :'Subject' %>
<%= f.text_field :subject, class: "form-control" %>
</div>

<div class="form-group">
<%= f.label :'Message' %>
<%= f.text_area :message, class: "form-control" %>
</div>

<div class="form-group">
<%= f.label :'Include Payment?' %>
<%= f.check_box :sent_money %>
</div>

<%= f.hidden_field :msg_date_time, value:Time.now %>

<%= f.submit "Save/Send", class: "btn btn-success btn-sm" %> <%= link_to "Cancel", messages_path, class: "btn btn-default btn-sm" %>

<% end %>

app/views/messages/show.html.erb
<div class="page-header" class="margin">
	<h3>Message
		<div class="pull-right">
			<%= link_to new_message_path, class: "btn btn-primary" do %>
				<i class="glyphicon glyphicon-plus"></i> Reply
			<% end %>
			<%= link_to messages_path, class: "btn btn-primary" do %>
				<i class="glyphicon glyphicon-th-list"></i> Back
			<% end %>
		</div>
	</h3>
</div>
<div class="col-md-7">
  <dl class="dl-horizontal">
	<dt>Message Date:</dt>
	<dd><%= @message.msg_date_time.strftime("%d-%b-%y %H:%M:%S") %></dd>
	<% if @message.msg_receiver == current_user.id %>
		<dt>From:</dt>
		<dd><%= @message.user.first_name %></dd>
	<% else %>
		<dt>To:</dt>
		<dd><%= User.find(@message.msg_receiver).first_name %></dd>
	<% end %>
	<dt>Subject:</dt>
	<dd><%= @message.subject %></dd>
	<dt>Message:</dt>
	<dd><%= @message.message %></dd>
	<dt>Included Money?:</dt>
	<% if@message.sent_money == false %>
		<dd><%= "No" %></dd>
	<% else %>
		<dd><%= "Yes" %></dd>
	<% end %>
	<% if @message.msg_status == true %>
		<dt></dt>
		<dd>
			<table class="table-bordered">
				<thead>
					<tr>
						<th>Currency</th>
						<th>Amt</th>
					</tr>
				</thead>
				<tbody>
					<% @message.money_txns.each do |money_txn| %>
						<tr>
							<td><%= money_txn.currency %></td>
							<td><%= money_txn.amt %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</dd>
	<% else %>
		<dt></dt>
		<dd>
		<div> <!-- Button trigger modal -->
			<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#addPayment">
			 Add Payment
			</button>
			<!-- Modal -->
			<div class="modal fade" id="addPayment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel">Add Payment</h4>
			      </div>
			      <div class="modal-body">
						<%= form_for @money_txn do |f| %>

						<div class="form-group">
							<%= f.label :'Currency' %>
							<%= f.select :currency, ["INR", "USD", "JPY", "AUD", "GBP", "EUR"], {prompt: "Select Currency"}, {class: "form-control chosen-select"} %>
						</div>
						<div class="form-group">
							<%= f.label :Amount %>
							<%= f.text_field :amt %>
						</div>
						<%= f.hidden_field :message_id, value: @message.id %>
						<%= f.hidden_field :received_from, value: @message.user.id %>
						<%= f.hidden_field :paid_to, value: @message.msg_receiver %>
						<br/>
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			        <%= f.submit "Submit", class: "btn btn-success" %>

						<% end %>
			       
			      </div>
			    </div>
			  </div>
			</div>
		</div> <!-- Button trigger modal ends here-->
		</dd>
		<dt></dt>
		<dd>
		<table class="table-bordered">
			<thead>
				<tr>
					<th>Currency</th>
					<th>Amt</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<% @message.money_txns.each do |money_txn| %>
				<tr>
					<td><%= money_txn.currency %></td>
					<td><%= money_txn.amt %></td>
					<td><%= link_to "Delete", money_txn_path(money_txn_id: money_txn.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		</dd>
	<% end %>
	</dl>
</div>


 

app/views/money_txns/index.html.erb
<div class="page-header" class="margin">
	<h3> Payments/Receipts </h3> 
</div>

<h4>Receipts</h4>
<table class="table table-stripped" id="messagesInboxTable" width="100%" border="0" cellspacing="0" cellpadding="0">
 <thead>
 	<tr>
 		<th>Date</th>
 		<th>Received From</th>
 		<th>Currecy</th>
 		<th>Amount</th>
 	</tr>
 </thead>
 <tbody>
 	<% @received_money_txns.each do |received_money_txn| %>
 	<tr>
 		<td><%= received_money_txn.message.msg_date_time.strftime("%d-%b-%y %H:%M:%S") %></td>
 		<td><%= User.find(received_money_txn.received_from).first_name %></td>
 		<td><%= received_money_txn.currency %></td>
 		<td><%= received_money_txn.amt %></td>
 	</tr>
 	<% end %>
 </tbody>
 </table>

<h4>Payments</h4>
 <table class="table table-stripped" id="messagesOutboxTable" width="100%" border="0" cellspacing="0" cellpadding="0">
 <thead>
 	<tr>
 		<th>Date</th>
 		<th>Paid To</th>
 		<th>Currecy</th>
 		<th>Amount</th>
 	</tr>
 </thead>
 <tbody>
 	<% @paid_money_txns.each do |paid_money_txn| %>
 	<tr>
 		<td><%= paid_money_txn.message.msg_date_time.strftime("%d-%b-%y %H:%M:%S") %></td>
 		<td><%= User.find(paid_money_txn.paid_to).first_name %></td>
 		<td><%= paid_money_txn.currency %></td>
 		<td><%= paid_money_txn.amt %></td>
 	</tr>
 	<% end %>
 </tbody>
 </table>